# Generated by Django 2.2 on 2019-12-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20191228_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secrets',
            fields=[
                ('id', models.UUIDField(default='4a8c4804-d3e9-4378-b6e3-a5e411a13e4d', editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='databaseitem',
            name='user_profile',
        ),
    ]
