# Generated by Django 2.2 on 2019-12-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20191229_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrets',
            name='id',
            field=models.UUIDField(default='840cecdf-f2ac-426d-8451-0d9128638f42', editable=False, primary_key=True, serialize=False),
        ),
    ]
