# Generated by Django 2.2 on 2019-12-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20191229_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrets',
            name='id',
            field=models.UUIDField(default='c4a87351-ad05-41d0-b3b9-63f7efaa5f4e', editable=False, primary_key=True, serialize=False),
        ),
    ]
