# Generated by Django 2.2 on 2019-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20191229_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrets',
            name='id',
            field=models.UUIDField(default='1c5a8138-e5c5-4e18-8d6c-4f248bd1d9c2', editable=False, primary_key=True, serialize=False),
        ),
    ]
