# Generated by Django 2.2 on 2019-12-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20191229_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrets',
            name='id',
            field=models.UUIDField(default='e758c2a7-76cf-407c-ad5f-62ab41abc1a0', editable=False, primary_key=True, serialize=False),
        ),
    ]
